name: Create wp-plugin zip
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: "srf-weather-widget.zip"
          directory: "./wp-plugin"
          path: "./srf-weather-widget"

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: 'srf-weather-widget'
          path: './wp-plugin/srf-weather-widget.zip'
