name: Create wp-plugin zip
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip archive
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: "wp-srf-weather-widget.zip"
          path: "./wp-plugin"

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: 'wp-srf-weather-widget.zip'
          path: '/wp-plugin/wp-srf-weather-widget.zip'
